/*
 * Font rendering implementation.
 *
 * FreeType renders 8-bit grayscale glyph bitmaps. Each bitmap is expanded
 * into a GX IA8 texture (8-bit intensity + 8-bit alpha, 4×4 tiles).
 * Glyphs are cached in a flat array indexed by (char_code - 32).
 *
 * Text is drawn as textured quads using GX_VTXFMT1 (XY position + RGBA
 * color + ST texture coordinates).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <gccore.h>

#include <ft2build.h>
#include <freetype/freetype.h>
#include <freetype/ftbitmap.h>

#include "font.h"

/* embedded font binary — generated by bin2s from data/inter_regular.bin */
#include "inter_regular_bin.h"

/* IA8 texture tile alignment: 4×4 pixels */
#define TEX_ALIGN 4

/* maximum ASCII codepoint we cache (inclusive) */
#define ASCII_MAX 126
#define ASCII_MIN 32
#define GLYPH_CACHE_SIZE (ASCII_MAX - ASCII_MIN + 1)

/* GX vertex format for textured quads (format 1) */
#define VTXFMT_TEXTured GX_VTXFMT1

/* ---- FreeType state ---- */

static FT_Library ft_library;
static FT_Face    ft_face;

/* ---- glyph cache ---- */

typedef struct {
    u16  texture_width;     /* IA8 texture width (tile-aligned) */
    u16  texture_height;    /* IA8 texture height (tile-aligned) */
    s16  bitmap_left;       /* X offset from pen to glyph origin */
    s16  bitmap_top;        /* Y offset from baseline to glyph top */
    s16  advance_x;         /* horizontal advance in pixels */
    u32 *texture_data;      /* IA8 texture data, memalign(32,...) */
    u8   rendered;          /* 1 if this glyph has been cached */
} glyph_cache_entry_t;

static glyph_cache_entry_t glyph_cache[GLYPH_CACHE_SIZE];

/* font metrics per size (cached at init) */
typedef struct {
    s16 ascender;
    s16 descender;
    s16 line_height;
    FT_UInt pixel_size;
} font_metrics_t;

static font_metrics_t metrics[FONT_SIZE_COUNT];

/* ---- helpers ---- */

static u16 align_to_tex_dim(u16 dim) {
    return (dim % TEX_ALIGN == 0) ? dim
                                  : TEX_ALIGN + dim - (dim % TEX_ALIGN);
}

/*
 * expand_bitmap_to_ia8 — convert FreeType 8-bit grayscale bitmap to IA8.
 *
 * IA8 layout: pairs of bytes [intensity][alpha] for each pixel.
 * Texture dimensions are aligned to 4-pixel boundaries.
 * Caller must free() the returned buffer.
 */
static u32 *expand_bitmap_to_ia8(const FT_Bitmap *bitmap,
                                  u16 *out_w, u16 *out_h) {
    u16 w = align_to_tex_dim(bitmap->width);
    u16 h = align_to_tex_dim(bitmap->rows);

    u32 *ia8 = (u32 *)memalign(32, w * h * 2);
    if (!ia8) return NULL;
    memset(ia8, 0, w * h * 2);

    u8 *src = bitmap->buffer;
    u8 *dst = (u8 *)ia8;

    for (u16 y = 0; y < bitmap->rows; y++) {
        for (u16 x = 0; x < bitmap->width; x++) {
            u16 texel_idx = y * w + x;
            /* IA8: first byte = intensity (from grayscale), second byte = alpha */
            dst[texel_idx * 2 + 0] = src[x];        /* intensity */
            dst[texel_idx * 2 + 1] = src[x];        /* alpha = intensity for clean text */
        }
        src += bitmap->pitch;
    }

    DCFlushRange(ia8, w * h * 2);

    *out_w = w;
    *out_h = h;
    return ia8;
}

/*
 * cache_glyph — render and cache a single glyph from all font sizes.
 *
 * Returns 0 on success (or if already cached), -1 on failure.
 */
static int cache_glyph(u32 char_code) {
    int idx = (int)char_code - ASCII_MIN;
    if (idx < 0 || idx >= GLYPH_CACHE_SIZE) return -1;
    if (glyph_cache[idx].rendered) return 0;

    FT_UInt gindex = FT_Get_Char_Index(ft_face, char_code);
    if (gindex == 0) return -1;

    FT_Error err = FT_Load_Glyph(ft_face, gindex, FT_LOAD_DEFAULT);
    if (err) return -1;

    err = FT_Render_Glyph(ft_face->glyph, FT_RENDER_MODE_NORMAL);
    if (err) return -1;

    const FT_Bitmap *bmp = &ft_face->glyph->bitmap;

    u16 tex_w, tex_h;
    u32 *ia8 = expand_bitmap_to_ia8(bmp, &tex_w, &tex_h);
    if (!ia8) return -1;

    glyph_cache[idx].texture_width  = tex_w;
    glyph_cache[idx].texture_height = tex_h;
    glyph_cache[idx].bitmap_left    = ft_face->glyph->bitmap_left;
    glyph_cache[idx].bitmap_top     = ft_face->glyph->bitmap_top;
    glyph_cache[idx].advance_x      = ft_face->glyph->advance.x >> 6;
    glyph_cache[idx].texture_data   = ia8;
    glyph_cache[idx].rendered       = 1;

    return 0;
}

/*
 * setup_textured_vtx_fmt — configure GX vertex format 1 for textured quads.
 *
 * Format: XY position (s16) + RGBA color (u8×4) + ST texture coords (f32).
 */
static void setup_textured_vtx_fmt(void) {
    GX_SetVtxDesc(GX_VA_POS,  GX_DIRECT);
    GX_SetVtxDesc(GX_VA_CLR0, GX_DIRECT);
    GX_SetVtxDesc(GX_VA_TEX0, GX_DIRECT);

    GX_SetVtxAttrFmt(VTXFMT_TEXTured, GX_VA_POS,  GX_POS_XY,  GX_S16,   0);
    GX_SetVtxAttrFmt(VTXFMT_TEXTured, GX_VA_CLR0, GX_CLR_RGBA, GX_RGBA8, 0);
    GX_SetVtxAttrFmt(VTXFMT_TEXTured, GX_VA_TEX0, GX_TEX_ST,  GX_F32,   0);
}

/*
 * restore_position_only_vtx_fmt — reset to GX_VTXFMT0 for solid-color quads.
 */
static void restore_position_only_vtx_fmt(void) {
    GX_ClearVtxDesc();
    GX_SetVtxDesc(GX_VA_POS, GX_DIRECT);

	GX_SetVtxAttrFmt(GX_VTXFMT0, GX_VA_POS, GX_POS_XYZ, GX_F32, 0);

    GX_SetNumTexGens(0);
	GX_SetTevOrder(GX_TEVSTAGE0, GX_TEXCOORDNULL, GX_TEXMAP_NULL, GX_COLOR0A0);
    GX_SetTevOp(GX_TEVSTAGE0, GX_PASSCLR);
}

/* ---- public API ---- */

int font_init(void) {
    memset(glyph_cache, 0, sizeof(glyph_cache));

    /* init FreeType */
    FT_Error err = FT_Init_FreeType(&ft_library);
    if (err) return -1;

    /* load font from embedded binary */
    err = FT_New_Memory_Face(ft_library,
                             (const FT_Byte *)inter_regular_bin,
                             (FT_Long)inter_regular_bin_size,
                             0, &ft_face);
    if (err) return -1;

    /* pre-compute metrics for each font size */
    static const FT_UInt font_sizes[FONT_SIZE_COUNT] = {
        FONT_SIZE_TAB_BAR, FONT_SIZE_HEADER, FONT_SIZE_HINTS
    };
    for (int i = 0; i < FONT_SIZE_COUNT; i++) {
        FT_UInt px = font_sizes[i];
        FT_Set_Pixel_Sizes(ft_face, 0, px);

        metrics[i].pixel_size  = px;
        metrics[i].ascender    = px * ft_face->ascender  / ft_face->units_per_EM;
        metrics[i].descender   = px * ft_face->descender / ft_face->units_per_EM;
        metrics[i].line_height = metrics[i].ascender - metrics[i].descender;
    }

    return 0;
}

void font_shutdown(void) {
    for (int i = 0; i < GLYPH_CACHE_SIZE; i++) {
        if (glyph_cache[i].texture_data) {
            free(glyph_cache[i].texture_data);
            glyph_cache[i].texture_data = NULL;
        }
    }
    memset(glyph_cache, 0, sizeof(glyph_cache));

    if (ft_face) {
        FT_Done_Face(ft_face);
        ft_face = NULL;
    }
    if (ft_library) {
        FT_Done_FreeType(ft_library);
        ft_library = NULL;
    }
}

int font_draw_text(f32 x, f32 y, const char *text, font_size_id_t size,
                   GXColor color) {
    if (!text || !ft_face) return 0;

    /* set pixel size for this font size */
    FT_Set_Pixel_Sizes(ft_face, 0, metrics[size].pixel_size);

    /* switch to textured vertex format */
    setup_textured_vtx_fmt();

    /* texture environment: modulate texture alpha with vertex color */
    GX_SetNumTexGens(1);
    GX_SetTevOrder(GX_TEVSTAGE0, GX_TEXCOORD0, GX_TEXMAP0, GX_COLOR0A0);
    GX_SetTevOp(GX_TEVSTAGE0, GX_MODULATE);

    /* alpha blending for smooth text */
    GX_SetBlendMode(GX_BM_BLEND, GX_BL_SRCALPHA, GX_BL_INVSRCALPHA, GX_LO_CLEAR);

    /* set up texture coordinate generation */
    GX_SetTexCoordGen(GX_TEXCOORD0, GX_TG_MTX2x4, GX_TG_TEX0, GX_PNMTX0);

    s16 pen_x = (s16)x;
    s16 pen_y = (s16)(y + metrics[size].ascender);  /* y is baseline */

    int total_width = 0;

    for (const char *p = text; *p; p++) {
        u32 ch = (u32)(unsigned char)*p;
        if (ch < ASCII_MIN || ch > ASCII_MAX) {
            /* skip non-printable characters */
            continue;
        }

        /* ensure glyph is cached */
        cache_glyph(ch);

        int idx = ch - ASCII_MIN;
        glyph_cache_entry_t *g = &glyph_cache[idx];
        if (!g->rendered || !g->texture_data) continue;

        /* create GX texture object from cached glyph */
        GXTexObj tex_obj;
        GX_InitTexObj(&tex_obj, g->texture_data,
                      g->texture_width, g->texture_height,
                      GX_TF_IA8, GX_CLAMP, GX_CLAMP, GX_FALSE);
        GX_LoadTexObj(&tex_obj, GX_TEXMAP0);
        GX_InvalidateTexAll();

        /* draw glyph quad */
        s16 gx = pen_x + g->bitmap_left;
        s16 gy = pen_y - g->bitmap_top;
        u16 gw = g->texture_width;
        u16 gh = g->texture_height;

        GX_Begin(GX_QUADS, VTXFMT_TEXTured, 4);

        /* top-left */
        GX_Position2s16(gx, gy);
        GX_Color4u8(color.r, color.g, color.b, color.a);
        GX_TexCoord2f32(0.0f, 0.0f);

        /* top-right */
        GX_Position2s16(gx + (s16)gw, gy);
        GX_Color4u8(color.r, color.g, color.b, color.a);
        GX_TexCoord2f32(1.0f, 0.0f);

        /* bottom-right */
        GX_Position2s16(gx + (s16)gw, gy + (s16)gh);
        GX_Color4u8(color.r, color.g, color.b, color.a);
        GX_TexCoord2f32(1.0f, 1.0f);

        /* bottom-left */
        GX_Position2s16(gx, gy + (s16)gh);
        GX_Color4u8(color.r, color.g, color.b, color.a);
        GX_TexCoord2f32(0.0f, 1.0f);

        GX_End();

        pen_x += g->advance_x;
        total_width += g->advance_x;
    }

    /* restore solid-color vertex format for remaining draw calls */
    restore_position_only_vtx_fmt();

    return total_width;
}

int font_text_width(const char *text, font_size_id_t size) {
    if (!text || !ft_face) return 0;

    FT_Set_Pixel_Sizes(ft_face, 0, metrics[size].pixel_size);

    int width = 0;
    for (const char *p = text; *p; p++) {
        u32 ch = (u32)(unsigned char)*p;
        if (ch < ASCII_MIN || ch > ASCII_MAX) continue;

        cache_glyph(ch);

        int idx = ch - ASCII_MIN;
        if (glyph_cache[idx].rendered) {
            width += glyph_cache[idx].advance_x;
        }
    }
    return width;
}
